### ISSUE TITLE
Using an environment variable in `exclude`

### ISSUE THREAD

**Issue by ArthurFlageul** [ruzickap/action-my-broken-link-checker#101]
Not sure if it's a bug or not, but I've tried to use an environment variable in the `exclude` parameter but it doesn't see to work, and I'm not sure how to diagnose this further. 

**To Reproduce**
Try this:

```yaml
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
name: test

jobs:
  link-checker-test:
    name: Check broken links
    runs-on: ubuntu-latest
    env:
      LIST: |
        mycompany.*
        .*?github.com
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://example.com
          cmd_params: |
            --follow-sitemap-xml
            --skip-tls-verification
            --max-connections=4
            --color=always
           --exclude="$(echo ${LIST}|tr ' ' '|')"
```

I've tried various approaches but somehow $(...) doesn't seem to be executed, I guess the exlude take the $(echo) as/is?

**Expected behaviour**
Some ability to resolve $() in the `cmd_params` field.

Thanks for any input!

**Comment by ruzickap** [comment]
In your case I will try something like:

```yaml
      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://${{ steps.variables.outputs.BASE_DOMAIN }}
          cmd_params: '--exclude=(github.com|mycompany) --follow-sitemap-xml --color=always --max-connections=4 --buffer-size=8192 --skip-tls-verification'
```

And then you can try to extend it / improve it...
