### ISSUE TITLE
"Something went wrong" but no error message is displayed

### ISSUE THREAD

**Issue by gabek** [ruzickap/action-my-broken-link-checker#128]
**Describe the bug**

The action fails with the following:

```
*** ERROR: [2024-02-09 03:38:43] Something went wrong - see the errors above...
```

But no errors are displayed.

Do you have any ideas what might be making it fail, or how I can get more details to fix it?

**To Reproduce**

Run the action with the following settings:

```
with:
    url: https://owncast.online/docs
    cmd_params: --buffer-size=8192 --max-connections=10 --color=always --rate-limit=1 --max-connections-per-host 3 --exclude="opencollective.com|github.com|example.com|mydomain.com|sitemap" --verbose
```

**Comment by ruzickap** [comment]
Can you paste here the whole step to allow me to see all the parameters "with:" + "uses:" please?

**Comment by gabek** [comment]
Sure!  Thanks!

```yaml
runs-on: ubuntu-latest
    steps:
      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://owncast.online/docs
          cmd_params: '--buffer-size=8192 --max-connections=10 --color=always --rate-limit=1 --max-connections-per-host 3 --exclude="opencollective.com|github.com|example.com|mydomain.com|sitemap" --verbose'
```
