### ISSUE TITLE
Is --header parameter correctly passed?

### ISSUE THREAD

**Issue by Hurtak** [ruzickap/action-my-broken-link-checker#83]
**Describe the bug**
I am using the action as follows

```
jobs:
  my-broken-link-checker:
    name: Broken Links Check
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://petrhurtak.com
          cmd_params: >
            --timeout=30
            --buffer-size=10000
            --header="user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
            --color=always
            --verbose

```

And it fails with this error

```
invalid argument for flag `--header' (expected []string): invalid syntax
*** ERROR: [2022-07-30 16:56:24] Something went wrong - see the errors above...
```

So I am wondering if there is issue with how I specified the parameter or with how the action passes the params to muffet. 
Unfortunatelly there is not much docs on the Muffer side about how pass this parameter correctly, the only docs I found is this https://github.com/raviqqe/muffet/blob/main/.snapshots/TestHelp#L19

**Comment by ruzickap** [comment]
Hello - thanks for reporting it.

This is a problem of the way how the GitHub Action is parsing the command line. (You can see it when you use the `debug: true` in your GH Action parameter)

If I use the muffet on the command line - it is working working fine:

```
muffet --timeout=30 --buffer-size=10000 --header="user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36" --color=always --verbose https://petrhurtak.com
```

I'll look at it...

**Comment by Hurtak** [comment]
bumping so stale bot does not close it :)

**Comment by hleb-kastseika** [comment]
I faced with the same issue, are there any workaround for that?

**Comment by Hurtak** [comment]
Commenting so that the bot does not close this :)

**Comment by Hurtak** [comment]
commenting so the bot does not close it

**Comment by Hurtak** [comment]
:)

**Comment by Hurtak** [comment]
Hi @ruzickap, would you consider turning off / changing settings of the github-actions bot? It seems to be too aggressive with how often it wants to close the issues. But feel free to ignore this comment, I don't want to push any opinions on you about how you should run you own open source projects :)

**Comment by madhead** [comment]
Just try using single quotes around []string arguments, like headers and excludes.

```yml
jobs:
  my-broken-link-checker:
    name: Broken Links Check
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://petrhurtak.com
          cmd_params: >
            --timeout=30
            --buffer-size=10000
            --header='user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'
            --color=always
            --verbose

```
